[workspace]
resolver = "2"
members = [
    "crates/onx-primitives",
    "crates/onx-data-structures",
    "crates/onx-state-model",
    "crates/onx-transactions",
    "crates/onx-blocks",
    "crates/onx-execution",
    "crates/onx-payment-channels",
    "crates/onx-consensus",
    "crates/onx-networking",
    "crates/onx-sharding",
    "crates/onx-economics",
    "crates/onx-telemetry",
    "crates/onxd",
    "crates/onx-genesis",
    "crates/onx-rpc",
    "crates/onx-cli",
]
exclude = ["fuzz"]
